name: pyXZ
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - scipy
  - pandas
  - matplotlib
  - plotly
  - proplot
  - cartopy
  - rise
  - jupyter
  - jupyter_contrib_nbextensions